# Generated by Django 5.2.1 on 2025-09-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_meetinginvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinginvite',
            name='preferred_lang',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
