# Generated by Django 5.2.1 on 2025-09-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_meetinginvite_preferred_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinginvite',
            name='joined',
            field=models.BooleanField(default=False),
        ),
    ]
