# Generated by Django 5.2.1 on 2025-09-25 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_transcriptsegment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='perform_translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='transcriptsegment',
            name='call',
        ),
        migrations.RemoveField(
            model_name='transcriptsegment',
            name='speaker',
        ),
        migrations.AddField(
            model_name='transcriptsegment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transcriptsegment',
            name='language',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='transcriptsegment',
            name='translated_text',
            field=models.TextField(),
        ),
    ]
