# Generated by Django 5.2.1 on 2025-07-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_callsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
